### ISSUE TITLE
Display Concise Notification When Opponent is Checked

### ISSUE THREAD

**Issue by krabhi1** [JakubBraz/rust_chess#1]
**Description:**

Currently, there is no notification when an opponent is checked during a game. To improve user experience, a concise message should be displayed to inform the player when they have put their opponent in check.

**Steps to Reproduce:**
1. Play a game until an opponent is checked.
2. Observe that no notification is shown.

**Expected Behavior:**
A concise message should appear to inform the player that the opponent is checked. This can be implemented as a modal dialog or a toast notification.

**Comment by JakubBraz** [comment]
Good point.
Done, feature implemented.
![obraz](https://github.com/user-attachments/assets/bce338f4-34e4-48ca-bf62-bc9aee6531a5)
